# Generated by Django 5.1.5 on 2025-01-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='messaage',
            new_name='message',
        ),
    ]
